//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalWork20
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClientsOrderSomeStuffEntities : DbContext
    {
        public ClientsOrderSomeStuffEntities()
            : base("name=ClientsOrderSomeStuffEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<OrderList> OrderList { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<View_2> View_2 { get; set; }
        public virtual DbSet<View_1> View_1 { get; set; }
        public virtual DbSet<View_3> View_3 { get; set; }

        private static ClientsOrderSomeStuffEntities context;

        public static ClientsOrderSomeStuffEntities GetContext()
        {
            if (context == null) context = new ClientsOrderSomeStuffEntities();
            return context;
        }
    }
}
