//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalWork20
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int ServiceId { get; set; }
        public double ServiceCost { get; set; }
        public string PaymentMethod { get; set; }
    
        public virtual OrderList OrderList { get; set; }
        public virtual Services Services { get; set; }
    }
}
