//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalWork20
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderList
    {
        public int OrderId { get; set; }
        public int ClientId { get; set; }
        public double OrderCost { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Orders Orders1 { get; set; }
    }
}
