//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalWork20
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int OrderId { get; set; }
        public string ClientSurname { get; set; }
        public string ClientPhone { get; set; }
        public string ServiceName { get; set; }
        public double OrderCost { get; set; }
        public System.DateTime OrderDate { get; set; }
    }
}
