//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalWork20
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_2
    {
        public int ClientId { get; set; }
        public string ClientSurname { get; set; }
        public Nullable<double> Cost { get; set; }
    }
}
